name: Build AsciiDoc and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Deploy AsciiDoc
        uses: manoelcampos/asciidoctor-ghpages-action@v1
        with:
          pdf_build: false
          slides_build: false
