name: AsciiDoc Auto Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install Asciidoctor tools
      run: |
        gem install asciidoctor
        gem install asciidoctor-pdf

    - name: Make convert.sh executable
      run: chmod +x convert.sh

    - name: Convert AsciiDoc to HTML and PDF
      run: ./convert.sh

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: asciidoc-output
        path: output/

